DROP TABLE IF EXISTS guides CASCADE;

CREATE TABLE guides (
  id SERIAL PRIMARY KEY NOT NULL,
  country VARCHAR(255) NOT NULL,
  city VARCHAR(255) NOT NULL,
  price INTEGER NOT NULL,
  profile_picture VARCHAR(255) NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  languages VARCHAR(255)
);